dir = File.dirname(__FILE__)
require "#{dir}/resources/runners"
require "#{dir}/resources/runners/firefox_runner"
require "#{dir}/resources/spec_runner"
require "#{dir}/resources/spec_file_runner"
require "#{dir}/resources/spec_dir_runner"
require "#{dir}/resources/file"
require "#{dir}/resources/dir"
require "#{dir}/resources/web_root"
require "#{dir}/resources/suite"
require "#{dir}/resources/suite_finish"
